# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 326ed2b77320c116748b89e8c716fb29584e80b3f06b3f21f4cf0abbb5695c2f2821a08a061a127d6f05726d5265d4c137ad4439fe5832d2a9a8fa6d61646ab6


test:
  secret_key_base: cb29f98391921029688b6393e1747bfccc235e98d32d3a78cc5801c27c3bc1a38e93bd1b3aeeb99fea26f8875f15354b86e3f74cbacb22c70249e2e063890796

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: bf3e14e657927c7d0ee01f409f0fbfb700b348d0e410caf356f68ea4db12201126db75cfa6c6299e14c5966b56c4e74bd24610212a702976c4820511ebc9de7e

